### PR TITLE
Move custom nginx config to a different file

### PR DESCRIPTION
**Pull request by flamingspaz**
Moving it to a different file allows us to add/mount our own custom configuration.

### CODE REVIEW

**Comment by gdestuynder** [comment]
@flamingspaz i approved but didnt merge yet - im wondering:
would this work for your configuration, if we had a location = / {...} with all the cruft, then an additional `custom.conf` for the `proxy_pass` location?

This would ensure all reqs have the correct HTTPS redirect / harder to mess up custom configs and disable https by mistake for example

**Comment by gdestuynder** [comment]
from irc/slack chat:
>  s/custom.conf/bypass_proxy.conf/
is probably the best solution to make things clear

also: can comment out the CSP header (though if u dont ill do it) since its more of an example, but can break some apps "by default"

**Comment by gdestuynder** [comment]
in fact, i just did it except for the CSP comment ;p

**Comment by gdestuynder** [comment]
@yousef just looking for your review of my review then ill merge

**Comment by flamingspaz** [comment]
r+

**Pull request merged**
