### PR TITLE
Add a note about redirect_uri as it's one of the major parameter you …

### PR DESCRIPTION
**Pull request by gdestuynder**
…need when setting up OIDC

### CODE REVIEW

**Comment by metadave** [comment]
Does the example `docker` command need be updated as well?

**Comment by gdestuynder** [comment]
the variable currently cannot be passed as an environment variable to docker (i.e. `-e redirect_uri_path=xxx` would not work)

**Comment by andrewkrug** [comment]
@gdestuynder looks like you also need to fixup the .travis.yml file so this doesn't fail.

**Comment by gdestuynder** [comment]
https://github.com/mozilla-iam/mozilla.oidc.accessproxy/issues/13 for travis

**Pull request merged**
